app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('movie', function(){
    $s = new \App\Movies\TMDB();
    $s->search('star wars')->each(function(\Tmdb\Model\Movie $movie){
        echo "<li>"
            . $movie->getTitle()
            . " - " . $movie->getPopularity()
            . " - " . $movie->getId()
            . "</li>";
    });
    dd($s->get(11));
});


Route::get('mmdb', function(){
    return view('mmdb.app');
});

Route::get('popular',  ['uses' => 'MoviesController@popular', 'as' => 'movies.popular']);
Route::get('top',  ['uses' => 'MoviesController@top', 'as' => 'movies.top']);
Route::get('upcoming',  ['uses' => 'MoviesController@upcoming', 'as' => 'movies.upcoming']);

Route::get('movies/search', ['uses' => 'MoviesController@search', 'as' => 'movies.search']);
Route::get('movies/poster', ['uses' => 'MoviesController@all', 'as' => 'movies.poster']);
Route::resource('movies', 'MoviesController');

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>MyMovieDataBase</title>

	<link href="{{ url('css/app.css') }}" rel="stylesheet">

    <link href="{{ url('css/player.css') }}" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="{{ url('css/selectize.bootstrap3.min.css') }}">
    <link rel="stylesheet" href="{{ url('css/select-movie.css') }}">

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <style>

        .thumbnail {
            position:relative;
            overflow:hidden;
        }

        .caption {
            position:absolute;
            top:0;
            right:0;
            background:rgba(0, 0, 0, 0.7);
            width:100%;
            height:100%;
            padding:2%;
            display: none;
            text-align:center;
            color:#fff !important;
            z-index:2;
        }
    </style>

</head>

<body>

    @include('navigation')

	@yield('content')

    @include('footer')

    @include('scripts')

</body>
</html>

resources/views/footer.blade.php
<footer>
    <p class="text-center">
        This product uses the TMDb API but is not endorsed or certified by TMDb.
    </p>
</footer>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/navigation.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('movies.index') }}">MMDB - MyMovieDataBase</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ route('movies.index') }}">Movies</a></li>
                <li><a href="{{ route('movies.poster') }}">Poster view</a></li>
                <!--<li><a href="{{ route('movies.popular') }}">Popular</a></li>
                <li><a href="{{ route('movies.top') }}">Top</a></li>
                <li><a href="{{ url('movies/create') }}">Add movie</a></li>-->
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if (Auth::guest())
                <li><a href="/auth/login">Login</a></li>
                <li><a href="/auth/register">Register</a></li>
                @else
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/auth/logout">Logout</a></li>
                    </ul>
                </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/scripts.blade.php
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>

<script src="{{url('js/jquery.js')}}"></script>
<script src="{{url('js/selectize.min.js')}}"></script>
<script src="{{url('js/selectize-standalone.min.js')}}"></script>

<script src="{{ url('js/select-movie.js') }}"></script>

<script src="{{ url('js/bootstrap-rating-input.min.js') }}"></script>


<script src="{{ url('js/player.js') }}"></script>

<script>
    $( document ).ready(function() {

        $('.thumbnail').hover(
            function(){
                $(this).find('.caption').slideDown(250); //.fadeIn(250)
            },
            function(){
                $(this).find('.caption').slideUp(250); //.fadeOut(205)
            }
        );

    });
</script>