app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('movie', function(){
    $s = new \App\Movies\TMDB();
    $s->search('star wars')->each(function(\Tmdb\Model\Movie $movie){
        echo "<li>"
            . $movie->getTitle()
            . " - " . $movie->getPopularity()
            . " - " . $movie->getId()
            . "</li>";
    });
    dd($s->get(11));
});


Route::get('mmdb', function(){
    return view('mmdb.app');
});

Route::get('popular',  ['uses' => 'MoviesController@popular', 'as' => 'movies.popular']);
Route::get('top',  ['uses' => 'MoviesController@top', 'as' => 'movies.top']);
Route::get('upcoming',  ['uses' => 'MoviesController@upcoming', 'as' => 'movies.upcoming']);

Route::get('movies/search', ['uses' => 'MoviesController@search', 'as' => 'movies.search']);
Route::get('movies/poster', ['uses' => 'MoviesController@all', 'as' => 'movies.poster']);
Route::resource('movies', 'MoviesController');

app/Http/Controllers/MoviesController.php
<?php namespace App\Http\Controllers;



use App\Movies\Repository\MovieRepositoryInterface;
use App\Movies\TMDB;
use App\User;
use Carbon\Carbon;
use Illuminate\Contracts\Pagination\Paginator;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Response;
use Tmdb\Model\Movie;

class MoviesController extends CrudController {

    private $tmdb;
    public function __construct(MovieRepositoryInterface $repo)
    {
        parent::__construct($repo, null, 'movie', 'Filmer');
    }


    public function index($data = [])
    {
        $instances = $this->repo->paginate(10);
        $instances->setPath(route('movies.index'));

        return view("{$this->route}.index",[
                $this->route => $instances,
                'links' => $this->editLinks('index')
            ] + $data);
    }


    public function show($id, $data = [])
    {
        $instance = $this->repo->find($id);
        if($instance->awards == null){
            $this->repo->updateImdbData($id);
        }
        if($instance->video_path == null){
            $this->repo->updateVideoData($id);
        }
        return parent::show($id, $data);
    }

    public function store(){
        $instance = $this->storePartial();
        $instance->tmdb_id = Input::get('tmdb_id');
        $this->repo->updateTmdbData($instance->id);
        $this->repo->updateImdbData($instance->id);
        return $this->redirect($instance);
    }

    public function search(TMDB $repo){
        $q = Input::get('q');
        $data = $repo->search($q)->map(function(Movie $d) use ($repo){
            return [
                'title' => $d->getTitle(),
                'id' => $d->getId(),
                'year' => Carbon::createFromTimestamp($d->getReleaseDate()->getTimestamp())->year,
                'vote' => $d->getVoteAverage()
            ];
        });

        return Response::json(compact('data'));
    }

    private function preview($a, $title){
        $movies = Collection::make($a)->map(function($d){
            $obj = \App\Movies\Movie::where('tmdb_id', '=', $d['id'])->first();
            if($obj == null){
                $obj = \App\Movies\Movie::create([
                        'tmdb_id' => $d['id'],
                        'id' => $d['id']
                    ]
                );
                $this->repo->updateTmdbData($obj->id);
            }
            return $obj;
        });
        return view("movies.preview", compact('movies', 'title'));
    }

    public function all(){
        $movies = $this->repo->paginate(16);
        $movies->setPath(route('movies.poster'));

        $title = 'All movies';
        return view("movies.preview", compact('movies', 'title'));
    }

    public function latest(TMDB $repo){
        return $this->all();
        return $this->upcoming($repo);
    }

    public function upcoming(TMDB $repo){
        return $this->all();
        return $this->preview($repo->getApi()->getUpcoming()['results'], 'Upcoming movies');
    }

    public function popular(TMDB $repo){
        return $this->all();
        return $this->preview($repo->getApi()->getPopular()['results'], 'Popular movies');
    }

    public function top(TMDB $repo){
        return $this->all();
        return $this->preview($repo->getApi()->getTopRated()['results'], 'Top rated movies');
    }
}

resources/views/movies/create.blade.php
@extends('app')

@section('content')

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Add movie</h1>
                {{ Html::ul($errors->all()) }}
                {!! Form::open(array('url' => 'movies')) !!}
                @include('movies.form')
                {!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</section>

@endsection

resources/views/movies/edit.blade.php
@extends('app')

@section('content')

<section id="plot">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Edit movie</h1>
                {{ Html::ul($errors->all()) }}
                {!! Form::model($movie, array('class' => 'form-horizontal', 'role' => 'form', 'method' => 'PUT', 'route' => array('movies.update', $movie->id)))!!}

                @include('movies.form')

                {!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
                {!!Form::close() !!}

            </div>
        </div>
    </div>
</section>

@endsection

resources/views/movies/form.blade.php
<div class="form-group">
    <label for="select-movie">Movie:</label>
    <select name="tmdb_id" id="select-movie" class="movies" placeholder="Find a movie..."></select>
</div>

resources/views/movies/index.blade.php
@extends('app')
@section('content')
@foreach($movies as $movie)
@include('movies.partial')
@endforeach

<section>
    <div class="container">
        {!! $movies->render() !!}
    </div>
</section>
@include('movies.player-modal')

@endsection

resources/views/movies/partial.blade.php
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="thumb">
                    @if($movie->video_path)
                        <a href="#" data-toggle="modal" data-target="#videoModal"
                           data-theVideo="//www.youtube.com/embed/{{$movie->video_path}}">
                            <span class="play">&#9658;</span>
                            <div class="overlay"></div>
                        </a>
                    @else
                    <a href="{{ route('movies.show', $movie->id) }}">
                        <span class="play"></span>
                        <div class="overlay"></div>
                    </a>
                    @endif
                    <img src="{{ @$movie['poster_path'] ?: url('no-poster-w185.jpg') }}" style="height: 200px">
                </div>
            </div>
            <div class="col-md-8">
                <h3>{!! link_to_route('movies.show', $movie->title, $movie->id) !!}
                    <small>({{ $movie->release_date }})</small>
                     
                </h3>
                <h5>{!! $movie->tagline !!}</h5>

                <p>{{ $movie->overview }} </p>

            </div>
            <div class="col-md-2">
                <p>
                <div class="label label-default">{{$movie->vote}}</div>
                </p>
                <p>{{ $movie->runtime }}</p>

                <p>{{ $movie->genre }} </p>

                <p>{{ $movie->awards }} </p>

            </div>
        </div>
        <hr>
    </div>
</section>

resources/views/movies/player-modal.blade.php
<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <div>
                    <iframe width="100%" height="350" src=""></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/movies/preview.blade.php
@extends('app')
@section('content')


<div class="container">
    @foreach($movies->chunk(4) as $movieChunk)
        <div class="row">
        @foreach($movieChunk as $movie)
            @include('movies.thumb')
        @endforeach
        </div>
    @endforeach

    {!! $movies->render() !!}

</div>

@include('movies.player-modal')
@endsection

resources/views/movies/show.blade.php
@extends('app')

@section('content')

    @include('movies.partial')

    @include('movies.player-modal')

@endsection

resources/views/movies/thumb.blade.php
<div class="col-md-3">
    <div class="thumbnail">
        <div class="caption">
            <h3>{!! @$movie['title'] ? link_to_route('movies.show', $movie['title'], $movie['id']): 'title' !!}</h3>
            <h4>{{ @$movie['tagline'] ?: '' }}</h4>
            <p>{{ @$movie['overview'] ?substr($movie['overview'],0, 250): '' }}</p>
            <input data-max="10" data-min="1"  type="number" value="{{@$movie['vote'] ?: ''}}" name="your_awesome_parameter" id="some_id" class="rating" data-icon-lib="fa" data-active-icon="fa-heart" data-inactive-icon="fa-heart-o" data-clearable-icon="fa-trash-o"/>{{@$movie['vote'] ?: ''}}
            @if($movie->video_path)
                <a href="#" class="btn btn-link" data-toggle="modal" data-target="#videoModal"
                    data-theVideo="//www.youtube.com/embed/{{$movie->video_path}}"><span class="fa fa-play"></span></a>
            @endif
        </div>
        <img src="{{ @$movie['poster_path'] ?: url('no-poster-w185.jpg') }}" alt="...">


    </div>
</div>